function speCompareThermoInitialize(speGUI)
% speCompareThermoInitialize(speGUIobj)

% Copyright 1999-2011 Michael Frenklach
% $ Revision: 1.1 $
% Last modified: January 16, 2011

Hpanel = uipanel('parent',speGUI.Hfig,...
   'units','pixels',...
   'Position', [140 10 415 430],...
   'Visible', 'off'    );
speGUI.HthermoCompare.panel = Hpanel;

bkColor = [0.9 0.9 0.9];   % get(speGUI.Hfig,'Color')

speGUI.HthermoCompare.key = uicontrol('Parent',Hpanel,...
   'Style','text',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'center',...
   'FontSize', 14,...
   'Position', [100 400 210 25]);

uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [1 340 80 15],...
   'HorizontalAlignment', 'right',...
   'String', 'Temperature = ');
speGUI.HthermoCompare.T = uicontrol('Parent',Hpanel,...
   'Style', 'edit',...
   'BackgroundColor', 'white',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'center',...
   'Position', [83 340 100 20],...
   'String',get(speGUI.Hthermo.T,'String'),...
   'Callback', @(h,d) speGUI.displayCompareThermo() );
uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [184 340 30 15],...
   'HorizontalAlignment', 'left',...
   'String', 'K');
speGUI.HthermoCompare.P = uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [200 340 120 15],...
   'HorizontalAlignment', 'right',...
   'String', '');

speGUI.HthermoCompare.prop = uicontrol('Parent',Hpanel,...
   'Style', 'popupmenu',...
   'Position', [150 290 50 20],...
   'BackgroundColor', bkColor,...
   'ForegroundColor', 'blue',...
   'String',{'Cp' 'H' 'S' 'Hf'},...
   'Callback', @(h,d) speGUI.displayCompareThermo() );

speGUI.HthermoCompare.units = uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [60 290 80 15],...
   'HorizontalAlignment', 'center',...
   'ForegroundColor', 'blue',...
   'String','');

speGUI.HthermoCompare.table = uitable('Parent',Hpanel,...
   'Position',[10 0 390 280],...
   'RowName', [] );