function speThermoPanelInitialize(speGUI)
% speThermoPanelInitialize(speGUIobj)

% Copyright 1999-2013 Michael Frenklach
% Last modified: February 25, 2013

Hpanel = uipanel('parent',speGUI.Hfig,...
   'units','pixels',...
   'Position', [140 10 415 430],...
   'Visible', 'off'    );
speGUI.Hthermo.panel = Hpanel;
% speGUI.Hthermo.eval = @speGUI.evalThermoData;
speGUI.Hthermo.eval = @speGUI.displayThermoPanel;
speGUI.Hthermo.currentThermo = [];

bkColor = [0.9 0.9 0.9];   % get(speGUI.Hfig,'Color')

speGUI.Hthermo.key = uicontrol('Parent',Hpanel,...
   'Style','text',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'center',...
   'FontSize', 14,...
   'Position', [100 400 210 25]);

uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [20 375 40 20],...
   'HorizontalAlignment', 'left',...
   'String', 'Source:' );
speGUI.Hthermo.ref = uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'ForegroundColor', 'blue',...
   'Position', [65 375 230 20],...
   'HorizontalAlignment','left',...
   'String', ''                );
uicontrol('Parent',Hpanel,...
   'Style', 'pushbutton',...
   'Position', [20 355 40 20],...
   'HorizontalAlignment','left',...
   'String', 'Data' ,....                
   'Callback', @viewDataXml );
uicontrol('Parent',Hpanel,...
   'Style', 'pushbutton',...
   'Position', [70 355 40 20],...
   'HorizontalAlignment','left',...
   'String', 'Biblio' ,....                
   'Callback', @refs );
speGUI.Hthermo.id = uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [120 355 80 15],...
   'HorizontalAlignment', 'right',...
   'String', '');

uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [1 317 80 15],...
   'HorizontalAlignment', 'right',...
   'String', 'Temperature = ');
speGUI.Hthermo.T = uicontrol('Parent',Hpanel,...
   'Style', 'edit',...
   'BackgroundColor', 'white',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'center',...
   'Position', [83 315 100 20],...
   'String','300 500:500:3000',...
   'Callback', @(h,d) speGUI.displayThermoPanel );
uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [184 315 30 15],...
   'HorizontalAlignment', 'left',...
   'String', 'K');
uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [200 315 65 15],...
   'HorizontalAlignment', 'right',...
   'String', 'Pressure = 1');
speGUI.Hthermo.Punits = uicontrol('Parent',Hpanel,...
   'Style', 'popupmenu',...
   'Position', [270 320 50 15],...
   'BackgroundColor', bkColor,...
   'ForegroundColor', 'blue',...
   'String', {'atm' 'bar'},...
   'Callback', @(h,d) speGUI.displayThermoPanel );

uicontrol('Parent',Hpanel,...
   'Style', 'popupmenu',...
   'Position', [350 350 50 20],...
   'BackgroundColor', bkColor,...
   'ForegroundColor', 'blue',...
   'String',{'Plot' 'Cp' 'H' 'S' 'Hf'},...
   'Callback', @plot );

speGUI.Hthermo.table = uitable('Parent',Hpanel,...
   'Position',[10 0 390 280],...
   'ColumnWidth', { 50 80 80 80 80 },...
   'ColumnName',{'T (K)','Cp','H','S','Hf'},...
   'ColumnFormat',{'numeric','numeric','numeric','numeric','numeric'},...
   'RowName', [] ,...
   'Data', {} );

speGUI.Hthermo.cpUnits = uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [61 280 79 15],...
   'HorizontalAlignment', 'center',...
   'BackgroundColor', bkColor,...
   'ForegroundColor', 'blue',...
   'String','');
speGUI.Hthermo.hUnits = uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [141 280 79 15],...
   'HorizontalAlignment', 'center',...
   'BackgroundColor', bkColor,...
   'ForegroundColor', 'blue',...
   'String','');
speGUI.Hthermo.sUnits = uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [221 280 79 15],...
   'HorizontalAlignment', 'center',...
   'BackgroundColor', bkColor,...
   'ForegroundColor', 'blue',...
   'String','');
speGUI.Hthermo.hfUnits = uicontrol('Parent',Hpanel,...
   'Style', 'popupmenu',...
   'Position', [301 280 79 20],...
   'HorizontalAlignment', 'center',...
   'BackgroundColor', bkColor,...
   'ForegroundColor', 'blue',...
   'String',speGUI.hUnitsList,...
   'Callback', @changeUnits );


   function changeUnits(h,d)
   % switches units of Cp,H, S, and Hf
      speGUI.thermoUnitsIndex = get(h,'Value');
      speGUI.displayThermoPanel();
   end

   function plot(h,d)
      ind = get(h,'Value');  % 2-Cp, 3-H, 4-S, 5-Hf
      if ind == 1
         return
      else
         speGUI.plotThermoData(ind);
         set(h,'value',1);   % get back to diplaying 'Plot')
      end
   end

   function refs(h,d)
   % display bibliographic info
      dataRef = speGUI.Hthermo.currentThermo.DataRef;
      for i1 = 1:length(dataRef)
         b(i1) = ReactionLab.Util.PrIMeData.PrIMeBiblio(dataRef(i1).id);
      end
      s = speGUI.CurrentSpecies;
      b.view([s.Thermo.Id ' of ' s.PrimeId]);
   end
   function viewDataXml(h,d)
      ReactionLab.Util.gate2primeData('show',...
         {'primeId',speGUI.CurrentSpecies.PrimeId,speGUI.Hthermo.currentThermo.Id});
   end

end