function loadReactionSetWindow(obj)
% loadReactionSetWindow(ChemkinMechObj)
% set the first panel for loading
%   a chemkin file

% Copyright 1999-2012 Michael Frenklach
% $Revision: 1.1 $
% Last modified: February 12, 2012

Hchemkin.Hpanel = feval(obj.HpanelTemplate);

panelColor = get(Hchemkin.Hpanel,'BackgroundColor');

Hchemkin.title = uicontrol('Parent',Hchemkin.Hpanel,...
   'Style', 'text',...
   'BackgroundColor', panelColor,...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'left',...
   'Position', [10 400 325 20],...
   'FontSize', 10, ...
   'String','BUILD REACTION SET FROM CHEMKIN FILE');

Hchemkin.mechBtn = uicontrol('Parent',Hchemkin.Hpanel,...
   'Style', 'pushbutton',...
   'HorizontalAlignment', 'left',...
   'Position', [10 350 200 20],...
   'FontSize', 10, ...
   'String','Select Chemkin Mechanism File',...
   'Callback', @selectChemkinFile );
Hchemkin.mechFile = uicontrol('Parent',Hchemkin.Hpanel,...
   'Style', 'text',...
   'BackgroundColor', panelColor,...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'left',...
   'Position', [20 320 300 20],...
   'FontSize', 10, ...
   'String','');

Hchemkin.thermoBtn = uicontrol('Parent',Hchemkin.Hpanel,...
   'Style', 'pushbutton',...
   'HorizontalAlignment', 'left',...
   'Position', [10 250 200 20],...
   'FontSize', 10, ...
   'String','Upload Chemkin Thermo File',...
   'Enable', 'off', ...
   'Callback', @selectThermoFile );
Hchemkin.thermoFile = uicontrol('Parent',Hchemkin.Hpanel,...
   'Style', 'text',...
   'BackgroundColor', panelColor,...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'left',...
   'Position', [20 200 300 40],...
   'FontSize', 10, ...
   'String','');

Hchemkin.transportBtn = uicontrol('Parent',Hchemkin.Hpanel,...
   'Style', 'pushbutton',...
   'HorizontalAlignment', 'left',...
   'Position', [10 150 200 20],...
   'FontSize', 10, ...
   'String','Upload Chemkin Transport File',...
   'Enable', 'off', ...
   'Callback', @selectTransportFile );
Hchemkin.transportFile = uicontrol('Parent',Hchemkin.Hpanel,...
   'Style', 'text',...
   'BackgroundColor', panelColor,...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'left',...
   'Position', [20 120 300 20],...
   'FontSize', 10, ...
   'String','');

obj.Panels = {Hchemkin};

% Hchemkin.rkDictBtn = uicontrol('Parent',Hchemkin.panel,...
%    'Style', 'pushbutton',...
%    'HorizontalAlignment', 'left',...
%    'Position', [10 200 200 20],...
%    'FontSize', 10, ...
%    'String','Upload k_source Dictionary',...
%    'Enable', 'off', ...
%    'Callback', @selectRkDictFile );
% Hchemkin.rkDictFile = uicontrol('Parent',Hchemkin.panel,...
%    'Style', 'text',...
%    'BackgroundColor', panelColor,...
%    'ForegroundColor', 'blue',...
%    'HorizontalAlignment', 'left',...
%    'Position', [220 200 100 20],...
%    'FontSize', 10, ...
%    'String','');
% 
% % Create the button group
% Hbtns = uibuttongroup('parent',Hfig,...
%    'Units',   'pixels',...
%    'Position',[220 450 140 30],...
%    'BorderType', 'none',...
%    'BackgroundColor', figColor,...
%    'SelectionChangeFcn', @dataButtonGroup );
% Hid = uicontrol('Parent',Hbtns,...
%    'Style', 'togglebutton',...
%    'Position', [5 5 60 20],...
%    'String','Identity' );
% uicontrol('Parent',Hbtns,...
%    'Style', 'togglebutton',...
%    'Position', [70 5 60 20],...
%    'String', 'Thermo' );
% set(Hbtns,'SelectedObject', Hid );
% 
% speGUI.Hfig  = Hfig;
% speGUI.Hlist = Hlist;
% speGUI.Hbtns = Hbtns;
% 
% speGUI.speIdPanelInitialize();
% speGUI.speThermoPanelInitialize();
% speGUI.speThermoFilesInitialize();
% speGUI.Hthermo.panel = [speGUI.Hthermo.panel speGUI.Hfiles.panel];
% speGUI.speCompareThermoInitialize();
% speGUI.speGeomPanelInitialize();
% speGUI.Hid.panel = [speGUI.Hid.panel speGUI.Hgeom.panel];
% speGUI.Hcurrent = speGUI.Hid;
% 

   function selectChemkinFile(h,d)
      obj.load();
      obj.parse2text();
      mechStr = obj.StrMechFile;
      if isempty(mechStr), return, end
      set(Hchemkin.mechFile,'String',obj.MechFileName);
      % check if THERMO is inside the MECHANISM file
      if ~isempty(obj.ThermoTxt)
         obj.ThermoFileName = obj.MechFileName;
         set(Hchemkin.thermoFile,'String',obj.ThermoFileName);
         set(obj.BottomPanel.Hnext,'Enable','on');
      end
      set(Hchemkin.thermoBtn,'Enable','on');
   end

   function selectThermoFile(h,d)
      [str,fileName] = ReactionLab.Util.getTextFile('Nasa7 Thermo');
      if ~isempty(str)
         obj.ThermoTxt = str;
         obj.ThermoFileName = fileName;
         set(Hchemkin.thermoFile,'String',fileName);
         thArray = ReactionLab.ThermoData.Nasa7.parseTxt(obj.ThermoTxt,obj.ThermoFileName);
         obj.ThermoArray = thArray;
         set(obj.BottomPanel.Hnext,'Enable','on');
      end
   end
% 
%    function selectRkDictFile(h,d)
%       [c,fileName] = ReactionLab.Util.getExcelFile('Species Dictionary');
%       if ~isempty(c)
%          obj.SpeciesDictFileName = fileName;
%          obj.SpeciesDict = c;
%       end
%    end

end