function mainWindowInitialize(obj)
% mainWindowInitialize(ChemkinMechObj)
% sets the main window for loading 
%   a chemkin file

% Copyright 1999-2012 Michael Frenklach
% $Revision: 1.1 $
% Last modified: December 27, 2011

Hfig = figure('Position',[50 200 850 490],...
   'NumberTitle', 'off',...
   'Name', 'Load Chemkin file',...
   'tag','chemkin file',...
   'MenuBar', 'none',...
   'Resize','off' );
obj.Hfig  = Hfig;

figColor = get(obj.Hfig,'Color');

HbottomPanel = uipanel('parent',Hfig,...
   'BackgroundColor', figColor,...
   'units','normalized',...
   'Position', [0 0 0.4 0.1]);
Hprev = uicontrol('Parent',HbottomPanel,...
   'Style', 'pushbutton',...
   'Position', [110 10 60 20],...
   'String', 'Prev',...
   'Enable', 'off', ...
   'Callback', {@switchPanel -1} );
Hnext = uicontrol('Parent',HbottomPanel,...
   'Style', 'pushbutton',...
   'Position', [170 10 60 20],...
   'String', 'Next',...
   'Enable', 'off', ...
   'Callback', {@switchPanel +1} );
obj.BottomPanel.panel = HbottomPanel;
obj.BottomPanel.Hprev = Hprev;
obj.BottomPanel.Hnext = Hnext;


createRightPanel;
obj.HpanelTemplate = @createNewPanel;

obj.loadReactionSetWindow();
addPanel(ReactionLab.Util.PrIMeData.SpeciesDepot.SpeciesIdentity(obj),'SpeciesIdentity');
obj.CurrentPanelIndex = 1;
set(obj.CurrentPanel,'Visible','on');


   function HpanelTemplate = createNewPanel
      HpanelTemplate = uipanel('parent',Hfig,...
         'Visible','off',...
         'units','normalized',...
         'Position', [0 0.1 0.4 0.9]);
   end

    function createRightPanel
        HRightPanel = uipanel('parent',Hfig,...
           'units','normalized',...
           'Position', [0.4 0 0.6 1.0]);
        HtitleStr = {'Select Thermo File','Upload Species Dictionary'};
        Htitle2Str = {'Example Files','Example Files'};
        Htitle3Str = {'Prev/Next','Action'};
        Htitle4Str = {'','Converting from inchi to PrIMe ID'};
        HbuttonStr = {'<html><u>Thermo File Requirements</u></html>','<html><u>Species File Requirements</u></html>'};
        HPosition = {{[30 440 440 20],[50 380 420 60],[50 345 150 30],[30 305 440 20],[50 270 150 30],[30 230 440 20],[50 160 420 70],[30 115 440 20],[50 45 420 70]},...
                     {[30 440 440 20],[50 380 420 60],[50 355 150 30],[30 320 440 20],[50 285 150 30],[30 245 440 20],[50 175 420 70],[30 135 440 20],[50 35 420 100]}};
        HdescriptionStr = {'Press the button "Select thermo file" to upload a thermodynamic data file typically used in Chemkin projects.  This file will be used to determine the chemical composition of a given species.   Press the button below to view the requirements for the thermo file formatting.  A full example also can be downloaded under "Example Files".',...
            {'Upload a species dictionary with the name and corresponding IDs of the species.  Press the button below to view the requirements for the species dictionary formatting.  A full example also can be downloaded under "Example Files".'}};
        Hdescription2Str = {'<html><u>Thermo File</u></html>',...
            {'<html><u>Species Dictionary File</u></html>'}};
        Hdescription3Str = {'Once you have uploaded a thermo file or if you wish to skip uploading a thermo file press "Next" to begin identifying species.',...
            {'Remove: Delete the selected dictionaries from the list below.','Merge: Combine two or more species of the same format to one species dictionary.','Edit: View the species dictionary, show information for an individual species, and','        export the dictionary to an excel file.','Convert: Create a second species dictionary, converting the inchi IDs to PrIMe IDs.'}};
        Hdescription4Str = {'',...
            {'After selecting "convert", the builupDictionary file is created with all definite matches.','Verify: Accept the match found by PrIMe to add the species to the buildupDictionary.','    Reject it to find a match based on the thermo file''s chemical compositions.','Check by Composition: Resolve a species by selecting the correct match, then','    pressing "Select displayed".  If no match is correct, add it to the new species.','Submit to PrIMe: Submit new species to PrIMe by adding fields to properly','    identify the species.  After identifying all species, press "Submit displayed".'}};
        Hlink2Str = {'http://primekinetics.org/tutorials/therm.txt','http://primekinetics.org/tutorials/species_dictionary_inchi_id.xlsx'};
        Hfilename2Str = {'thermo.txt','species_dictionary_inchi_id.xlsx'};
        Htitle = uicontrol('Parent',HRightPanel,...
           'Style', 'text',...
           'Position', HPosition{1}{1},...
           'String', HtitleStr{1},...
           'HorizontalAlignment','left',...
           'FontWeight', 'bold');
        Hdescription = uicontrol('Parent',HRightPanel,...
           'Style', 'text',...
           'Position', HPosition{1}{2},...
           'HorizontalAlignment','left',...
           'String', HdescriptionStr{1});
        Hbutton = uicontrol('Parent',HRightPanel,...
           'Style', 'PushButton', ... 
           'Position', HPosition{1}{3},...
           'HorizontalAlignment','left',...
           'String', HbuttonStr{1},...
           'ForegroundColor',[0 0 1],...
           'Callback', @viewRequirements );
        Htitle2 = uicontrol('Parent',HRightPanel,...
           'Style', 'text',...
           'Position', HPosition{1}{4},...
           'HorizontalAlignment','left',...
           'String', Htitle2Str{1},...
           'FontWeight', 'bold');
        Hdescription2 = uicontrol('Parent',HRightPanel,...
           'Style', 'PushButton', ... 
           'Position', HPosition{1}{5},...
           'HorizontalAlignment','left',...
           'String', Hdescription2Str{1},...
           'ForegroundColor',[0 0 1],...
           'Callback', @downloadFile );
        Htitle3 = uicontrol('Parent',HRightPanel,...
           'Style', 'text',...
           'Position', HPosition{1}{6},...
           'HorizontalAlignment','left',...
           'String', Htitle3Str{1},...
           'FontWeight', 'bold');
        Hdescription3 = uicontrol('Parent',HRightPanel,...
           'Style', 'text',...
           'Position', HPosition{1}{7},...
           'HorizontalAlignment','left',...
           'String', Hdescription3Str{1});
        Htitle4 = uicontrol('Parent',HRightPanel,...
           'Style', 'text',...
           'Position', HPosition{1}{8},...
           'HorizontalAlignment','left',...
           'String', Htitle4Str{1},...
           'FontWeight', 'bold');
        Hdescription4 = uicontrol('Parent',HRightPanel,...
           'Style', 'text',...
           'Position', HPosition{1}{8},...
           'HorizontalAlignment','left',...
           'String', Hdescription4Str{1});
        obj.RightPanel.position = HPosition;
        obj.RightPanel.panel = HRightPanel;
        obj.RightPanel.title = Htitle;
        obj.RightPanel.description = Hdescription;
        obj.RightPanel.button = Hbutton;
        obj.RightPanel.title2 = Htitle2;
        obj.RightPanel.description2 = Hdescription2;
        obj.RightPanel.title3 = Htitle3;
        obj.RightPanel.description3 = Hdescription3;
        obj.RightPanel.title4 = Htitle4;
        obj.RightPanel.description4 = Hdescription4;
        obj.RightPanel.titleStr = HtitleStr;
        obj.RightPanel.descriptionStr = HdescriptionStr;
        obj.RightPanel.buttonStr = HbuttonStr;
        obj.RightPanel.title2Str = Htitle2Str;
        obj.RightPanel.description2Str = Hdescription2Str;
        obj.RightPanel.title3Str = Htitle3Str;
        obj.RightPanel.description3Str = Hdescription3Str;
        obj.RightPanel.title4Str = Htitle4Str;
        obj.RightPanel.description4Str = Hdescription4Str;
        obj.RightPanel.link2Str = Hlink2Str;
        obj.RightPanel.filename2Str = Hfilename2Str;
    end

   function switchPanel(hh,dd,inc)
      set(obj.CurrentPanel,'Visible','off');
      obj.CurrentPanelIndex = obj.CurrentPanelIndex + inc;
      set([Hprev Hnext],'Enable','on');
      setRightPanel
      if obj.CurrentPanelIndex == 1
         set(Hprev,'Enable','off');
      end
      if obj.CurrentPanelIndex == length(obj.Panels)
         set(Hnext,'Enable','off');
      end
      set(obj.CurrentPanel,'Visible','on');
   end

   function setRightPanel()
       set(obj.RightPanel.title,'String',obj.RightPanel.titleStr{obj.CurrentPanelIndex},'Position',obj.RightPanel.position{obj.CurrentPanelIndex}{1})
       set(obj.RightPanel.description,'String',obj.RightPanel.descriptionStr{obj.CurrentPanelIndex},'Position',obj.RightPanel.position{obj.CurrentPanelIndex}{2})
       set(obj.RightPanel.button,'String',obj.RightPanel.buttonStr{obj.CurrentPanelIndex},'Position',obj.RightPanel.position{obj.CurrentPanelIndex}{3})
       set(obj.RightPanel.title2,'String',obj.RightPanel.title2Str{obj.CurrentPanelIndex},'Position',obj.RightPanel.position{obj.CurrentPanelIndex}{4})
       set(obj.RightPanel.description2,'String',obj.RightPanel.description2Str{obj.CurrentPanelIndex},'Position',obj.RightPanel.position{obj.CurrentPanelIndex}{5})
       set(obj.RightPanel.title3,'String',obj.RightPanel.title3Str{obj.CurrentPanelIndex},'Position',obj.RightPanel.position{obj.CurrentPanelIndex}{6})
       set(obj.RightPanel.description3,'String',obj.RightPanel.description3Str{obj.CurrentPanelIndex},'Position',obj.RightPanel.position{obj.CurrentPanelIndex}{7})
       set(obj.RightPanel.title4,'String',obj.RightPanel.title4Str{obj.CurrentPanelIndex},'Position',obj.RightPanel.position{obj.CurrentPanelIndex}{8})
       set(obj.RightPanel.description4,'String',obj.RightPanel.description4Str{obj.CurrentPanelIndex},'Position',obj.RightPanel.position{obj.CurrentPanelIndex}{9})
   end

   function addPanel(newObj,prop)
      obj.(prop) = newObj;
      obj.Panels = [obj.Panels {newObj}];
   end

   function downloadFile(hh,dd)
       [filestr,status]=urlwrite(...
        obj.RightPanel.link2Str{obj.CurrentPanelIndex},...
        obj.RightPanel.filename2Str{obj.CurrentPanelIndex});
       msgbox(['The file named "' obj.RightPanel.filename2Str{obj.CurrentPanelIndex} '" was saved to "' filestr '"']) 
   end

    function viewRequirements(hh,dd)
        requirementArray={{'1. The file must be in text format (.txt).','2. Nasa polynomial coefficients must include a plus or minus sign before','    each exponent.   (i.e. 0.25000000e+01 not 0.25000000e 01)'},...
            {'1. The file must be in excel file format. (.xls or .xlsx)','2. No headers should be included','3. ID Type can be either "inchi" or "PrIMeID"','4. Column A of the excel file corresponds to the species name and Column B','    corresponds to the species ID'}};
        msgbox(requirementArray{obj.CurrentPanelIndex},'File Requirements','help')
   end
   
end