function H = displayCellArray(cellArray,title)
% display a cell array

% Copyright 1999-2012 Michael Frenklach
% $Revision: 1.0 $
% Last modified: February 13, 2012

H.cellArray = cellArray;

Hfig = figure('Position',[50 200 300 300],...
   'NumberTitle', 'off',...
   'Name', title,...
   'MenuBar', 'none' );
H.Hfig = Hfig;

Hedit = uimenu('Parent',Hfig,...
   'Label','Edit');
uimenu('Parent',Hedit,...
   'Label','Export as Excel',...
   'Callback', @saveAsExcel );
H.Hedit = Hedit;

Htools = uimenu('Parent',Hfig,...
   'Label','Tools');
uimenu('Parent',Htools,...
   'Label','Sort by key',...
   'Callback', {@sort 1} );
uimenu('Parent',Htools,...
   'Label','Sort by value',...
   'Callback', {@sort 2} );
uimenu('Parent',Htools,...
   'Label','Restore',...
   'Callback', @restore );
uimenu('Parent',Htools,...
   'Label','Total count',...
   'Separator','on',...
   'Callback', @count );
H.Htools = Htools;

Htable = uitable('Parent',Hfig,...
   'units','normalized',...
   'Position',[0 0 1 0.95],...
   'ColumnName', {'key' 'value'},...
   'columneditable', [false false],...
   'RowName', [],...
   'Data', cellArray );
H.Htable = Htable;

pos = get(Hfig,'Position');
colW = pos(3)*0.95/size(cellArray,2);
set(Htable,'ColumnWidth',{colW});


   function saveAsExcel(hh,dd)
      H.fileName = ReactionLab.Util.saveExcelFile(cellArray,title);
   end

   function sort(hh,dd,ind)
      cellArray = sortrows(cellArray,ind);
      set(Htable,'Data',cellArray);
   end

   function restore(hh,dd)
      set(Htable,'Data',H.cellArray);
   end

   function count(hh,dd)
      msgbox(['Total number of entries = ' int2str(size(cellArray,1))],' ','modal');
   end

end