function displayThermoTable(rxnGUI,r,T)
% displayThermoTable(rxnGUIobj,ReactionObj,T)
%
% displays a table of reaction thermo

% Copyright 1999-2016 Michael Frenklach
% Modified: November 21, 2010
% Modified:     June  2, 2016, myf: fixed typo with plotting Keq

hu = rxnGUI.hUnits;
su = rxnGUI.sUnits;

[eqK,~,u,dH,dS,dG] = r.keq(T,rxnGUI.eqKunits);
deltaH = ReactionLab.Units.conv_energy(dH,'K',rxnGUI.hUnits);
deltaS = ReactionLab.Units.conv_energy(dS,'K',rxnGUI.sUnits);
deltaG = ReactionLab.Units.conv_energy(dG,'K',rxnGUI.hUnits);

lenT = min(length(T),30);
hRows = 20*(lenT+3);
pos = [200 250 405 hRows];
Hfig = figure(...
   'Position', pos,...
   'NumberTitle', 'off',...
   'Name', r.Eq,...
   'Tag', 'rxnThermoTable',...
   'MenuBar', 'none',...
   'Resize', 'off');

Hplot = uimenu('Parent',Hfig,'Label','Plot');
uimenu('Parent', Hplot,...
   'Label', 'Delta-H',...
   'Callback', { @localPlot deltaH ['\DeltaH  [' strrep(hu,'_',' ') ']']} );
uimenu('Parent', Hplot,...
   'Label', 'Delta-S',...
   'Callback', { @localPlot deltaS ['\DeltaS  [' strrep(su,'_',' ') ']']} );
uimenu('Parent', Hplot,...
   'Label', 'Delta-G',...
   'Callback', { @localPlot deltaG ['\DeltaG  [' strrep(hu,'_',' ') ']']} );
uimenu('Parent', Hplot,...
   'Label', 'Keq',...
   'Callback', { @localPlotKeq eqK ['Keq  [' strrep(u,'_',' ') ']']} );

uitable('Parent',Hfig,'Visible','on',...
        'Position',[0 0 402 hRows-30],...
        'ColumnWidth', { 60 80 80 80 80 },...
        'ColumnName',{'T (K)','Delta-H','Delta-S','Delta-G','Keq'},...
        'ColumnFormat',{'numeric','numeric','numeric','numeric','numeric'},...
        'RowName', [] ,...
        'Data', [ T; deltaH; deltaS; deltaG; eqK]' );

uicontrol('Parent',Hfig,...
   'Style', 'text',...
   'Position', [61 hRows-30 79 15],...
   'HorizontalAlignment', 'center',...
   'String',hu);
uicontrol('Parent',Hfig,...
   'Style', 'text',...
   'Position', [141 hRows-30 79 15],...
   'HorizontalAlignment', 'center',...
   'String',su);
uicontrol('Parent',Hfig,...
   'Style', 'text',...
   'Position', [221 hRows-30 79 15],...
   'HorizontalAlignment', 'center',...
   'String',hu);
uicontrol('Parent',Hfig,...
   'Style', 'text',...
   'Position', [301 hRows-30 79 15],...
   'HorizontalAlignment', 'center',...
   'String',u);

   
   function localPlot(h,d,y,yLabel)
      figure('NumberTitle','off', 'Name',r.Eq);
      plot(T,y,'o');
      xlabel('T [K]')
      ylabel(yLabel)
   end

   function localPlotKeq(h,d,y,yLabel)
      figure('NumberTitle','off', 'Name',r.Eq);
      semilogy(1./T,y,'o');
      xlabel('1/T [1/K]')
      ylabel(yLabel)
   end

end