function rxnIdPanelInitialize(rxnGUI)
% rxnIdPanelInitialize(rxnGUIobj)

% Copyright 1999-2016 Michael Frenklach
% Modified:  November 20, 2010
% Modified:   January  1, 2016, myf: added select column
% Modified:  February 25, 2016, myf: comments out (for now) 'Flip reaction'
% Modified: March 4, 2016, Jim Oreluk: made changed to graphics objects to
% work in Matlab 2013. Original code is commented above changes. 

Hpanel = uipanel('parent',rxnGUI.Hfig,...
   'units','pixels',...
   'Position', [350 20 290 400],...
   'Visible', 'on');
rxnGUI.Hid.panel = Hpanel;
bkColor = [0.9 0.9 0.9];

rxnGUI.Hid.eqn = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'ForegroundColor', 'blue',...
      'FontSize', 10,...
      'Position', [20 370 250 25],...
      'ButtonDownFcn',@rxnReverse);
   
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [1 345 60 20],...
      'HorizontalAlignment', 'left',...
      'String', 'Reaction ID:');
rxnGUI.Hid.rxnId = uicontrol('Parent',Hpanel,...
      'Style', 'pushbutton',...
      'ForegroundColor', 'blue',...
      'String', '',...
      'Position',[65 350 60 20],...
      'HorizontalAlignment', 'left',...
      'Callback', @viewRxnXml );

uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'String','Rate ID: ',...
      'Position',[130 345 60 20],...
      'HorizontalAlignment', 'right');
rxnGUI.Hid.rateId = uicontrol('Parent',Hpanel,...
      'Style', 'pushbutton',...
      'ForegroundColor', 'blue',...
      'String', '',...
      'Position',[195 350 65 20],...
      'HorizontalAlignment', 'left',...
      'Callback', @viewRateXml );
   
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'String','Rate Law: ',...
      'Position',[1 325 60 20],...
      'HorizontalAlignment', 'left');
rxnGUI.Hid.rateLaw = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'ForegroundColor', 'blue',...
      'String', '',...
      'Position',[65 325 100 20],...
      'HorizontalAlignment', 'left');
   
rxnGUI.Hid.unitsA = uicontrol('Parent',Hpanel,'Visible','on',...
   'Style', 'popupmenu',...
   'String', rxnGUI.aUnitsList,...
   'Position', [0 300 75 20],...
   'HorizontalAlignment', 'center',...
   'Callback', @changeAunits);
rxnGUI.Hid.unitsE = uicontrol('Parent',Hpanel,'Visible','on',...
   'Style', 'popupmenu',...
   'String', rxnGUI.eUnitsList,...
   'Position', [115 300 65 20],...   
   'HorizontalAlignment', 'center',...
   'Callback', @changeEunits);
Htable = uitable('Parent',Hpanel,'Visible','on',...
   'Position',[0 50 287 250 ],...
   'ColumnWidth', { 75 40 65 64 40},...
   'ColumnFormat', {'numeric' 'numeric' 'numeric' 'char' 'logical'},...
   'ColumnEditable', [ false false false false true ], ...
   'ColumnName', {'A' 'n' 'E' ' ' 'select'},...
   'RowName', [] ,...
   'Data', {} ,...
   'CellEditCallback', @selectTableItem );
rxnGUI.Hid.rkTable = Htable;
Haction = uicontrol('Parent',Hpanel,...
   'Style', 'popupmenu',...
   'Position', [224 305 60 20],...
   'BackgroundColor', bkColor,...
   'ForegroundColor', 'blue',...
   'String',{'Action' 'Show xml' 'Compare' 'Compare all' ...
                      'Reverse k' 'Flip reaction' 'Clear all'},...
   'Callback', @selectTableAction );
rxnGUI.Hid.Action = Haction;

HfoPanel = uipanel('Visible', 'off',...
   'parent',Hpanel,...
   'units','pixels',...
   'Position', [0 0 290 40],...
   'BorderType','none');
rxnGUI.Hid.foPanel = HfoPanel;

uicontrol('Parent',HfoPanel,...
      'Style', 'text',...
      'Position', [1 10 40 20],...
      'HorizontalAlignment', 'left',...
      'String', 'Falloff:');
rxnGUI.Hid.foType = uicontrol('Parent',HfoPanel,...
      'Style', 'text',...
      'ForegroundColor', 'blue',...
      'String', '',...
      'Position',[45 10 100 20],...
      'HorizontalAlignment', 'left');
rxnGUI.Hid.foParam = uicontrol('Visible','off',...
      'Parent',HfoPanel,...
      'Style', 'pushbutton',...
      'ForegroundColor', 'blue',...
      'String', 'Parameters',...
      'Position',[155 10 100 20],...
      'HorizontalAlignment', 'left',...
      'Callback', []);
         
   function changeAunits(h,d)
   % change units of A
      rxnGUI.aUnitsIndex = get(rxnGUI.Hid.unitsA,'Value');
      rxnGUI.buttonClick();
   end
   function changeEunits(h,d)
   % change units of A
      rxnGUI.eUnitsIndex = get(rxnGUI.Hid.unitsE,'Value');
      rxnGUI.buttonClick();
   end

   function viewRxnXml(hh,dd)
   % display the rxn source file
      ReactionLab.Util.gate2primeData('show',{'primeId',get(hh,'String')});
   end
   function viewRateXml(hh,dd)
   % display the rxn rate source file
      ReactionLab.Util.gate2primeData('show',...
         {'primeId',get(rxnGUI.Hid.rxnId,'String'),get(hh,'String')});
   end

    function selectTableAction(hh,dd)
        %data = Htable.Data;
        data = get(Htable, 'Data');
        ind = find([data{:,5}]);  % index(es) of selected rk's in table
        % if isempty(ind) && (hh.Value~=4 && hh.Value~=6)
        if isempty(ind) && (get(hh, 'Value') ~=4 && get(hh, 'Value') ~=6)
            return;
        end
        primeIds = get(Htable,'UserData');
        % switch hh.Value
        switch get(hh, 'Value')
            case 1
                return;
            case 2  % show xml file
                ReactionLab.Util.gate2primeData('show',...
                  {'primeId',get(rxnGUI.Hid.rxnId,'String'),primeIds{ind}});
          case 3  % plot comparing selected rk's
              ii = find([data{:,5}]);
              if length(ii) == 1
                  rxnGUI.displayRateCoefPanel(rxnGUI.CurrentReaction);
              else
                  rxnGUI.compareRK(ii);
              end
          case 4  % compare all rk's from the table
              nRK = size(data,1);
              if nRK == 1
                  rxnGUI.displayRateCoefPanel(rxnGUI.CurrentReaction);
              else
                  rxnGUI.compareRK(1:size(data,1));
              end
          case 5  % reverse rk direction
              rxnGUI.flipRKdirection(ind);
          case 6  % reverse reaction direction
              %             rxnGUI.CurrentReaction.flipDirection();
              %             rxnGUI.displayIdPanel(rxnGUI.CurrentReaction)
          case 7  % clear all
              % Htable.Data(:,5) = {false};
              hData = get(Htable, 'Data');
              hData(:,5) = {false};
              set(Htable, 'Data', hData);
      end

%       drawnow;
   end

   function selectTableItem(hh,dd)
      %rxnGUI.CurrentReaction.SelectedIndex =find([hh.Data{:,5}]);
      hData = get(hh, 'Data');
      rxnGUI.CurrentReaction.SelectedIndex = find([hData{:,5}]);
      % if Haction.Value ~= 2  % proceed only for 'Show xml'
      if get(Haction, 'Value') ~= 2
          return
      end
      ind = dd.Indices;
      if isempty(ind)
         return;
      end
      selectTableAction(Haction,[]);
   end

end