function rxnIdPanelInitialize(rxnGUI)
% rxnIdPanelInitialize(rxnGUIobj)

% Copyright 1999-2010 Michael Frenklach
% $Revision: 1.1 $
% Last modified: November 20, 2010

Hpanel = uipanel('parent',rxnGUI.Hfig,...
   'units','pixels',...
   'Position', [350 20 290 400],...
   'Visible', 'on');
rxnGUI.Hid.panel = Hpanel;

rxnGUI.Hid.eqn = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'ForegroundColor', 'blue',...
      'FontSize', 10,...
      'Position', [20 370 250 25],...
      'ButtonDownFcn',@rxnReverse);
   
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [1 345 60 20],...
      'HorizontalAlignment', 'left',...
      'String', 'Reaction ID:');
rxnGUI.Hid.rxnId = uicontrol('Parent',Hpanel,...
      'Style', 'pushbutton',...
      'ForegroundColor', 'blue',...
      'String', '',...
      'Position',[65 350 60 20],...
      'HorizontalAlignment', 'left',...
      'Callback', @viewRxnXml );

uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'String','Rate ID: ',...
      'Position',[130 345 60 20],...
      'HorizontalAlignment', 'right');
rxnGUI.Hid.rateId = uicontrol('Parent',Hpanel,...
      'Style', 'pushbutton',...
      'ForegroundColor', 'blue',...
      'String', '',...
      'Position',[195 350 65 20],...
      'HorizontalAlignment', 'left',...
      'Callback', @viewRateXml );
   
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'String','Rate Law: ',...
      'Position',[1 325 60 20],...
      'HorizontalAlignment', 'left');
rxnGUI.Hid.rateLaw = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'ForegroundColor', 'blue',...
      'String', '',...
      'Position',[65 325 100 20],...
      'HorizontalAlignment', 'left');
   
rxnGUI.Hid.unitsA = uicontrol('Parent',Hpanel,'Visible','on',...
   'Style', 'popupmenu',...
   'String', rxnGUI.aUnitsList,...
   'Position', [0 300 75 20],...
   'HorizontalAlignment', 'center',...
   'Callback', @changeAunits);
rxnGUI.Hid.unitsE = uicontrol('Parent',Hpanel,'Visible','on',...
   'Style', 'popupmenu',...
   'String', rxnGUI.eUnitsList,...
   'Position', [135 300 65 20],...   
   'HorizontalAlignment', 'center',...
   'Callback', @changeEunits);
rxnGUI.Hid.rkTable = uitable('Parent',Hpanel,'Visible','on',...
   'Position',[0 50 287 250 ],...
   'ColumnWidth', { 75 60 65 70},...
   'ColumnFormat', {'numeric' 'numeric' 'numeric' 'char'},...
   'ColumnName', {'A' 'n' 'E' ' '},...
   'RowName', [] ,...
   'Data', {},...
   'CellSelectionCallback', @localTableAction );


HfoPanel = uipanel('Visible', 'off',...
   'parent',Hpanel,...
   'units','pixels',...
   'Position', [0 0 290 40],...
   'BorderType','none');
rxnGUI.Hid.foPanel = HfoPanel;

uicontrol('Parent',HfoPanel,...
      'Style', 'text',...
      'Position', [1 10 40 20],...
      'HorizontalAlignment', 'left',...
      'String', 'Falloff:');
rxnGUI.Hid.foType = uicontrol('Parent',HfoPanel,...
      'Style', 'text',...
      'ForegroundColor', 'blue',...
      'String', '',...
      'Position',[45 10 100 20],...
      'HorizontalAlignment', 'left');
rxnGUI.Hid.foParam = uicontrol('Visible','off',...
      'Parent',HfoPanel,...
      'Style', 'pushbutton',...
      'ForegroundColor', 'blue',...
      'String', 'Parameters',...
      'Position',[155 10 100 20],...
      'HorizontalAlignment', 'left',...
      'Callback', []);
         
   function changeAunits(h,d)
   % change units of A
      rxnGUI.aUnitsIndex = get(rxnGUI.Hid.unitsA,'Value');
      rxnGUI.buttonClick();
   end
   function changeEunits(h,d)
   % change units of A
      rxnGUI.eUnitsIndex = get(rxnGUI.Hid.unitsE,'Value');
      rxnGUI.buttonClick();
   end

   function viewRxnXml(hh,dd)
   % display the rxn source file
      ReactionLab.Util.gate2primeData('show',{'primeId',get(hh,'String')});
   end
   function viewRateXml(hh,dd)
   % display the rxn rate source file
      ReactionLab.Util.gate2primeData('show',...
         {'primeId',get(rxnGUI.Hid.rxnId,'String'),get(hh,'String')});
   end

   function localTableAction(hh,dd)
   % display the individual rxn rate source file
      ind = dd.Indices;
      if ~isempty(ind) && ind(2) == 4
         primeIds = get(hh,'UserData');
         ReactionLab.Util.gate2primeData('show',...
            {'primeId',get(rxnGUI.Hid.rxnId,'String'),primeIds{ind(1)}});
      end
   end

   function rxnReverse(hh,dd)
      
   end

end