function rxnRateCoefPanelInitialize(rxnGUI)
% rxnRateCoefPanelInitialize(rxnGUIobj)

% Copyright 1999-2010 Michael Frenklach
% $ Revision: 1.1 $
% Last modified: November 20, 2010

Hpanel = uipanel('parent',rxnGUI.Hfig,...
   'units','pixels',...
   'Position', [350 20 290 400],...
   'Visible', 'off'    );
rxnGUI.Hrk.panel = Hpanel;

rxnGUI.Hrk.eqn = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'ForegroundColor', 'blue',...
      'FontSize', 10,...
      'Position', [20 370 250 25],...
      'ButtonDownFcn',@rxnReverse);

y = 300;
dy = 70;
rxnGUI.Hrk.pLabel = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'HorizontalAlignment', 'right',...
      'String', 'Pressure = ');
rxnGUI.Hrk.P = uicontrol('Parent',Hpanel,...
      'Style', 'edit',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 20],...
      'String','1',...
      'CallBack', @localDisplay );
rxnGUI.Hrk.pUnits = uicontrol('Parent',Hpanel,...
      'Style', 'popupmenu',...
      'Position', [205 y 80 15],...
      'HorizontalAlignment', 'left',...
      'String', rxnGUI.pUnitsList,...
      'Callback',@changePunits);

y = y - dy;
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'HorizontalAlignment', 'right',...
      'String', 'Temperature = ');
rxnGUI.Hrk.T = uicontrol('Parent',Hpanel,...
      'Style', 'edit',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 20],...
      'String','1000',...
      'CallBack', @localDisplay );
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [205 y 30 15],...
      'HorizontalAlignment', 'left',...
      'String', 'K');
      
y = y - dy;
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'HorizontalAlignment', 'right',...
      'String', 'k_forward');
rxnGUI.Hrk.Forw = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 15]);
rxnGUI.Hrk.aUnits = uicontrol('Parent',Hpanel,...
      'Style', 'popupmenu',...
      'Position', [205 y 80 15],...
      'HorizontalAlignment', 'left',...
      'String',rxnGUI.aUnitsList,...
      'Callback',@changeAunits);
   
y = y - dy;
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'HorizontalAlignment', 'right',...
      'String', 'r_reverse');
rxnGUI.Hrk.Rev = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 15] );
   
y = y - dy;
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'HorizontalAlignment', 'right',...
      'String', 'Keq = ');
rxnGUI.Hrk.eqK = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 15] );


   function localDisplay(h,d)
      rxnGUI.buttonClick();
   end

   function changeAunits(h,d)
   % switches units of rk
      rxnGUI.aUnitsIndex = get(h,'Value');
      rxnGUI.buttonClick();
   end
   function changeKeqUnits(h,d)
   % switches units of Keq
      rxnGUI.eqKunitsIndex = get(h,'Value');
      rxnGUI.buttonClick();
   end
   function changePunits(h,d)
   % switches units of Pressure
      rxnGUI.pUnitsIndex = get(h,'Value');
      rxnGUI.buttonClick();
   end

   function rxnReverse(hh,dd)
      
   end

end