function rxnThermoPanelInitialize(rxnGUI)
% rxnThermoPanelInitialize(rxnGUIobj)

% Copyright 1999-2010 Michael Frenklach
% $ Revision: 1.1 $
% Last modified: November 20, 2010

Hpanel = uipanel('parent',rxnGUI.Hfig,...
   'units','pixels',...
   'Position', [350 20 290 400],...
   'Visible', 'off'    );
rxnGUI.Hthermo.panel = Hpanel;

rxnGUI.Hthermo.eqn = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'ForegroundColor', 'blue',...
      'FontSize', 10,...
      'Position', [20 370 250 25],...
      'ButtonDownFcn',@rxnReverse);

y = 300;
dy = 70;
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'Tag', 'rxnTempLabel',...
      'HorizontalAlignment', 'right',...
      'String', 'Temperature = ');
rxnGUI.Hthermo.T = uicontrol('Parent',Hpanel,...
      'Style', 'edit',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 20],...
      'String','1000',...
      'CallBack',@localDisplay );
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [205 y 30 15],...
      'HorizontalAlignment', 'left',...
      'String', 'K');
      
y = y - dy;
dy = 60.;
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'HorizontalAlignment', 'right',...
      'String', 'delta-H =');
rxnGUI.Hthermo.dH = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 15]);
rxnGUI.Hthermo.dHunits = uicontrol('Parent',Hpanel,...
      'Style', 'popupmenu',...
      'Position', [205 y 80 15],...
      'HorizontalAlignment', 'left',...
      'String',rxnGUI.hUnitsList,...
      'Callback',@changeEunits);
   
y = y - dy;
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'HorizontalAlignment', 'right',...
      'String', 'delta-S =');
rxnGUI.Hthermo.dS = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 15] );
rxnGUI.Hthermo.dSunits = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [205 y 60 15],...
      'HorizontalAlignment', 'left',...
      'String', rxnGUI.sUnits );
      
y = y - dy;
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'HorizontalAlignment', 'right',...
      'String', 'delta-G = ');
rxnGUI.Hthermo.dG = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 15] );
rxnGUI.Hthermo.dGunits = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [205 y 60 15],...
      'HorizontalAlignment', 'left',...
      'String', rxnGUI.hUnits );
   
y = y - dy;
uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'HorizontalAlignment', 'right',...
      'String', 'Keq = ');
rxnGUI.Hthermo.eqK = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 15] );
rxnGUI.Hthermo.eqKunits = uicontrol('Parent',Hpanel,...
      'Style', 'popupmenu',...
      'Position', [205 y 80 15],...
      'HorizontalAlignment', 'left',...
      'String',rxnGUI.eqKunitsList,...
      'Callback',@changeKeqUnits);

   function localDisplay(h,d)
      rxnGUI.buttonClick();
   end

   function changeEunits(h,d)
   % switches units of H, S, and G
      rxnGUI.thermoUnitsIndex = get(h,'Value');
      set(rxnGUI.Hthermo.dSunits,'String',rxnGUI.sUnits);
      set(rxnGUI.Hthermo.dGunits,'String',rxnGUI.hUnits);
      rxnGUI.buttonClick();
   end
   function changeKeqUnits(h,d)
   % switches units of Keq
      rxnGUI.eqKunitsIndex = get(h,'Value');
      rxnGUI.buttonClick();
   end

   function rxnReverse(hh,dd)
      
   end

end