function rxnWindowInitialize(rxnGUI)
% rxnWindowInitialize(rxnGUobj)
% sets the main window for  reaction

% Copyright 1999-2015 Michael Frenklach
% Modified: November 20, 2010
% Modified:  January  2, 2015, myf: fixed localFind

Hfig = figure('Position',[50 200 650 490],...
   'NumberTitle', 'off',...
   'Name', 'reactions',...
   'Tag', 'reactions',...
   'MenuBar', 'none',...
   'Resize','off' );

figColor = get(Hfig,'Color');

uicontrol('Parent',Hfig,...
   'Style', 'edit',...
   'BackgroundColor', 'white',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'left',...
   'Position', [10 450 310 20],...
   'Tag', 'rxnEdit',...
   'Callback', @localFind );
Hlist = uicontrol('Parent',Hfig,...
   'Style', 'listbox',...
   'BackgroundColor', 'white',...
   'Position', [10 20 310 400],...
   'Tag', 'rxnList',...
   'Callback', @buttonGroup );

% Create the button group
Hbtns = uibuttongroup('parent',Hfig,...
   'Units',   'pixels',...
   'Position',[350 450 210 30],...
   'Tag','speSelectionBtns',...
   'BorderType', 'none',...
   'BackgroundColor', figColor,...
   'SelectionChangeFcn', @buttonGroup );
uicontrol('Parent',Hbtns,...
   'Style', 'togglebutton',...
   'Position', [5 5 60 20],...
   'Tag', 'rxnIdentityBtn',...
   'String','Identity',...
   'Value', 0 );
uicontrol('Parent',Hbtns,...
   'Style', 'togglebutton',...
   'Position', [70 5 60 20],...
   'Tag', 'rxnThermoBtn',...
   'String', 'Thermo',...
   'Value', 0 );
uicontrol('Parent',Hbtns,...
   'Style', 'togglebutton',...
   'Position', [135 5 60 20],...
   'Tag', 'rxnRateCoefBtn',...
   'String', 'Rate Coef',...
   'Value', 0 );

rxnGUI.Hfig  = Hfig;
rxnGUI.Hlist = Hlist;
rxnGUI.Hbtns = Hbtns;

rxnIdPanelInitialize(rxnGUI);
rxnThermoPanelInitialize(rxnGUI);
rxnRateCoefPanelInitialize(rxnGUI);


   function localFind(h,d)
      req = get(h,'string');
      if isempty(req)
         rxnGUI.RxnList = rxnGUI.PrevRxnList;  % restore original
         rxnGUI.setWindowList();
         return
      end
      rxnList = rxnGUI.RxnList;  % get the current rxn set
      c = textscan(req, '%s', 'delimiter', ' ,+=');
      rxnSpe2find = upper(c{:});
      rxnKeyList = get(Hlist,'string');
      c2 = upper(rxnKeyList);
      for i2 = 1:length(rxnSpe2find)
         c3 = strfind(c2,rxnSpe2find{i2});
         ind = find(cellfun(@isempty,c3));
         c2(ind) = [];
         rxnList = rxnList.remove(ind);
      end
      set(Hlist,'String',c2,'Value',1);
      rxnGUI.RxnList = rxnList;
      buttonGroup([],[]);
   end


   function buttonGroup(h,d)
      rxnGUI.buttonClick();
   end


end