function wratecoef(r,action)
% wratecoef(reactionObject)

% Copyright 1999-2007 Michael Frenklach
% $Revision: November 21, 2006$

switch action
   case 'close'
      LOCAL_close;
   case 'open'
      LOCAL_open;
   case 'update'
      Hkey = findobj(gcf,'Tag','rkEq');
      setappdata(Hkey,'curRxn',r);
      LOCAL_display;
   case 'display'
      LOCAL_display;
   otherwise
      error(['undefined action: ' action])
end
return


function LOCAL_close
%
   Hbtn = findobj(gcbf,'Tag','rxnRateCoefBtn');
   set(getappdata(Hbtn,'Hpanel'),'Visible','off');
return
      

function LOCAL_open
%
   Hfig = gcf;
   Hbtn = findobj(Hfig,'Tag','rxnRateCoefBtn');
   Hpanel = getappdata(Hbtn,'Hpanel');
   if ~isempty(Hpanel)
      set(Hpanel,'Visible','on');
   else
      LOCAL_initial(Hfig);
   end
   wlist(reaction,'list');
return


function LOCAL_initial(Hfig)
%
   Hpanel = uipanel('Parent',Hfig,...
      'units','pixels',...
      'Position', [350 20 290 400]);
      
   Hrxn = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'ForegroundColor', 'blue',...
      'FontSize', 12,...
      'Position', [20 370 250 25],...
      'Tag', 'rkEq');

   y = 300;
   dy = 70;
   HpresLabel = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'Tag', 'rkPresLabel',...
      'HorizontalAlignment', 'right',...
      'String', 'Pressure = ');
   Hpres = uicontrol('Parent',Hpanel,...
      'Style', 'edit',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 20],...
      'Tag', 'rkPres',...
      'String','1',...
      'CallBack','wratecoef(reaction,''display'');');
   HpresUnits = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [205 y 30 15],...
      'Tag', 'rkPresUnits',...
      'HorizontalAlignment', 'left',...
      'UserData', {'atm','torr','bar'},...
      'String', 'atm',...
      'ButtonDownFcn',{@localChangeUnitsP Hpanel});
   
   y = y - dy;
   HtempLabel = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'Tag', 'rkTempLabel',...
      'HorizontalAlignment', 'right',...
      'String', 'Temperature = ');
   Htemp = uicontrol('Parent',Hpanel,...
      'Style', 'edit',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 20],...
      'Tag', 'rkTemp',...
      'String','1000',...
      'CallBack','wratecoef(reaction,''display'');');
   HtempUnits = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [205 y 30 15],...
      'Tag', 'rkTempUnits',...
      'HorizontalAlignment', 'left',...
      'String', 'K');

   y = y - dy;
   HkFlabel = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'Tag', 'kFlabel',...
      'HorizontalAlignment', 'right',...
      'String', 'k_forward = ');
   HkF = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 15],...
      'Tag', 'kF');
   HkFunits = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [205 y 80 15],...
      'Tag', 'kFunits',...
      'HorizontalAlignment', 'left',...
      'UserData',{'mol/cm3','cm-3';'cm3/mol','cm3'},...
      'ButtonDownFcn',{@localChangeUnitsC Hpanel});
   
   y = y - dy;
   HkRlabel = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'Tag', 'kRlabel',...
      'HorizontalAlignment', 'right',...
      'String', 'k_reverse = ');
   HkR = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 15],...
      'Tag', 'kR');
   
   y = y - dy;
   HeqKlabel = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [5 y 80 15],...
      'Tag', 'eqKlabel',...
      'HorizontalAlignment', 'right',...
      'String', 'Keq = ');
   HeqK = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'BackgroundColor', 'white',...
      'ForegroundColor', 'blue',...
      'HorizontalAlignment', 'center',...
      'Position', [95 y 100 15],...
      'Tag', 'eqK');
   HeqKunits = uicontrol('Parent',Hpanel,...
      'Style', 'text',...
      'Position', [205 y 80 15],...
      'Tag', 'eqKunits',...
      'HorizontalAlignment', 'left',...
      'ButtonDownFcn',{@localChangeUnitsC Hpanel});
 
   fieldH = [ Hrxn, Htemp, HkF, HkFunits, HkR, ...
              Hpres, HpresUnits, HeqK, HeqKunits ];
   dataH =  [ HkF, HkFunits, HkR, HeqK, HeqKunits ];
   Hbtn = findobj(Hfig,'Tag','rxnRateCoefBtn');
   setappdata(Hbtn,'Hpanel',Hpanel);
   setappdata(Hbtn,'fieldH',fieldH);
   setappdata(Hbtn,'dataH', dataH);
return


function LOCAL_display
%
   Hbtn = findobj(gcf,'Tag','rxnRateCoefBtn');
   Hpanel = getappdata(Hbtn,'Hpanel');
   Hkey = findobj(Hpanel,'Tag','rkEq');
   r = getappdata(Hkey,'curRxn');
   HunitsC = findobj(Hpanel,'Tag','kFunits');
   unitsC = get(HunitsC,'UserData');
   Htemp = findobj(Hpanel,'Tag','rkTemp');
   T = str2num(get(Htemp,'String'));
   if isempty(T) || any(T <= 0)
      LOCAL_updateDisplay(Hbtn,r,[]);
      Hdlg = errordlg('Temperature values must be greater than 0',...
                      'evaluation of rate coefficient','modal');
      waitfor(Hdlg);
      return;
   end
   k = get(r,'k_forward');
   if length(k) > 1
      type = get(r,'type');
      ref = type;
   else
      type = get(k,'type');
      ref = k.ref;
   end
   type = get(k(1),'type');
   if length(k)==1 && any(strcmpi(type,{'mass action' 'third body'}))
      set([findobj(Hpanel,'Tag','rkPresLabel'), ...
           findobj(Hpanel,'Tag','rkPres'     ), ...
           findobj(Hpanel,'Tag','rkPresUnits')],...
                          'Visible','off'    )    ;
      P = [];
      unitsP = '';
   else
      set([findobj(Hpanel,'Tag','rkPresLabel'), ...
           findobj(Hpanel,'Tag','rkPres'     ), ...
           findobj(Hpanel,'Tag','rkPresUnits')],...
                          'Visible','on'     )    ;
      Hpres = findobj(Hpanel,'Tag','rkPres');
      P = str2num(get(Hpres,'string'));
      if isempty(P) || any(P < 0)
         LOCAL_updateDisplay(Hbtn,r,[]);
         Hdlg = errordlg('Pressure values must not be negative',...
                      'evaluation of rate coefficient','modal');
         waitfor(Hdlg);
         return;
      end
      HunitsP = findobj(Hpanel,'Tag','rkPresUnits');
      uList = get(HunitsP,'UserData');
      unitsP = char(uList{1});
   end
   reversible = get(r,'reversible');
   if length(T) > 1 || length(P) > 1
      if length(P) < 2 || length(T) == 1
         if reversible
            [kR,eqK,uKeq,kF,ukF] = evalrevk(r,unitsC,T,P,unitsP);
            if length(eqK) ~= length(kF)
               eqK = repmat(eqK,size(kF));
            end
            table(k,get(r),ref,T,P,unitsP,kF,ukF,kR,'',eqK,uKeq);
         else
            [kF,ukF] = eval(k,unitsC{2,1},T,P,unitsP);
            table(k,get(r),ref,T,P,unitsP,kF,ukF);
            kR = []; eqK = []; uKeq = '';
         end
      else
         plot3d(r,unitsC,T,P,unitsP)
      end
      kF = []; kR = []; eqK = [];
      ukF = ''; uKeq = '';
   else
      if reversible
         [kR,eqK,uKeq,kF,ukF] = evalrevk(r,unitsC,T,P,unitsP);
      else
         [kF,ukF] = eval(k,unitsC{2,1},T,P,unitsP);
         kR = []; eqK = []; uKeq = '';
      end
   end
   LOCAL_updateDisplay(Hbtn,r,kF,ukF,kR,eqK,uKeq);
return


function LOCAL_updateDisplay(Hbtn,r,kF,ukF,kR,eqK,uKeq)
% update diplay of values
   data = getappdata(Hbtn,'dataH');
   if isempty(kF) 
      set(data,'String','');
      return;
   end
   for H = getappdata(Hbtn,'fieldH')
      switch get(H,'Tag')
         case 'rkEq'
            set(H,'String',get(r));
         case 'kF'
            set(H,'String',sprintf('%.2e',kF));
         case 'kFunits'
            set(H,'String',ukF);
         case 'kR'
            set(H,'String',sprintf('%.2e',kR));
         case 'eqK'
            set(H,'String',sprintf('%.2e',eqK));
         case 'eqKunits'
            set(H,'String',uKeq);
      end
   end
return


function localChangeUnitsC(hh,dd,Hpanel)
% switch concentration units
   Hunits = findobj(Hpanel,'Tag','kFunits');
   unitsList = get(Hunits,'UserData');
   unitsList = unitsList(:,[2:end 1]);
   set(Hunits,'UserData',unitsList);
   LOCAL_display;
return


function localChangeUnitsP(hh,dd,Hpanel)
% switch pressure units
   Hunits = findobj(Hpanel,'Tag','rkPresUnits');
   unitsList = get(Hunits,'UserData');
   uPrev = unitsList{1};
   unitsList = unitsList([2:end 1]);
   set(Hunits,'UserData',unitsList);
   uP = unitsList{1};
   HunitsP = findobj(Hpanel,'Tag','rkPresUnits');
   set(HunitsP,'String',uP);
   Hpres = findobj(Hpanel,'Tag','rkPres');
   prevP = str2num(get(Hpres,'string'));
   switch uP
      case 'atm'
         P = prevP ./ 1.01325;
      case 'torr'
         P = prevP .* 760;
      case 'bar'
         P = prevP .* 1.01325 ./ 760;
      otherwise
         error(['undefined pressure units' uP])
   end
   set(Hpres,'String',num2str(P));
return