function speGeomPanelInitialize(speGUI)
% speGeomPanelInitialize(speGUIobj)

% Copyright 1999-2015 Michael Frenklach
% Modified: July 15, 2012
% Modified: January 1, 2015, myf

Hpanel = uipanel('parent',speGUI.Hfig,...
   'units','pixels',...
   'Position', [420 10 400 430],...
   'BackgroundColor',get(speGUI.Hfig,'Color') + 0.03,...
   'Visible', 'on');
% Hpanel = uipanel('parent',speGUI.Hfig,...
%    'units','pixels',...
%    'Position', [420 10 400 430],...
%    'Visible', 'on');
speGUI.Hgeom.panel = Hpanel;

rScale  = 0.55;
[x,y,z] = sphere(30);
speGUI.Hgeom.xSphere = x * rScale;
speGUI.Hgeom.ySphere = y * rScale;
speGUI.Hgeom.zSphere = z * rScale;
speGUI.Hgeom.elementsData = ReactionLab.SpeciesData.SpeciesStructure.Atom.loadElementsData;

% 2D-3D switch
Hbtns = uibuttongroup('parent',Hpanel,...
   'Units',   'normalized',...             % pixels
   'Position',[0 0 0.35 0.07],...        % [0 0 1 0.07]   [10 0  140 30]
   'BorderType', 'none',...
   'BackgroundColor', get(Hpanel,'BackgroundColor'),...
   'SelectionChangeFcn', @(h,d) speGUI.displayGeomPanel );
H2D = uicontrol('Parent',Hbtns,...
   'Units',   'pixels',...
   'Style', 'togglebutton',...
   'Position', [5 5 60 20],...
   'String','2D' );
uicontrol('Parent',Hbtns,...
   'Units',   'pixels',...
   'Style', 'togglebutton',...
   'Position', [70 5 60 20],...
   'String', '3D' );
set(Hbtns,'SelectedObject', H2D );
speGUI.Hgeom.Hbtns = Hbtns;

% link to ChemSpider
uicontrol('Parent',Hpanel,...
   'Units', 'pixels',...
   'Style', 'pushbutton',...
   'Position',[320 5 70 20],...
   'String', 'ChemSpider',...
   'Callback', @go2chemSpider );

% axes panel
speGUI.Hgeom.panel2D = uipanel('parent',Hpanel,...
   'Units','normalized',...
   'Position', [0 0.07 1 0.93]);    % [0 30 250 370]
speGUI.Hgeom.panel3D = uipanel('parent',Hpanel,...
   'Visible', 'off',...
   'Units','normalized',...
   'Position', [0 0.07 1 0.93],...
   'BackgroundColor',[0 0 0] );   % [0 0 0.45]
speGUI.Hgeom.currentAxesPanel = [];
speGUI.Hgeom.currentSpecies = [];


   function go2chemSpider(h,d)
      speInchi = speGUI.CurrentSpecies.InChI;
      searchStr = ['http://www.chemspider.com/Search.aspx?q=' speInchi];
      web(searchStr,'-browser');
   end

end