function speIdPanelInitialize(speGUI)
% speIdPanelInitialize(speGUIobj)

% Copyright 1999-2013 Michael Frenklach
% Last modified: February 25, 2013

Hpanel = uipanel('parent',speGUI.Hfig,...
   'units','pixels',...
   'Position', [150 10 250 430],...
   'Visible', 'off');
speGUI.Hid.panel = Hpanel;
speGUI.Hid.eval = @speGUI.displayIdPanel;

speGUI.Hid.speKey = uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'center',...
   'FontSize', 14,...
   'Position', [20 400 210 25]);

uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [20 370 60 15],...
   'HorizontalAlignment', 'left',...
   'String', 'Name(s):');
speGUI.Hid.speName = uicontrol('Parent',Hpanel,...
   'Style', 'edit',...
   'BackgroundColor', 'white',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'left',...
   'Position', [20 310 210 60],...
   'Max', 10    );

uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [20 290 100 15],...
   'HorizontalAlignment', 'left',...
   'String', 'Formula(s):');
speGUI.Hid.speFormula = uicontrol('Parent',Hpanel,...
   'Style', 'edit',...
   'BackgroundColor', 'white',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'left',...
   'Position', [20 230 210 60],...
   'Max', 10     );
uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'Position', [20 210 210 15],...
   'HorizontalAlignment', 'left',...
   'String', 'Elemental Composition:');
speGUI.Hid.speElemSymbol = uicontrol(Hpanel,...
   'Style', 'edit',...
   'BackgroundColor', 'white',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'left',...
   'Position', [20 150  70 60],...
   'Max', 10 );
speGUI.Hid.speElemNumber = uicontrol('Parent',Hpanel,...
   'Style', 'edit',...
   'BackgroundColor', 'white',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'left',...
   'Position', [100 150  60 60],...
   'Max', 10           );
%    uicontrol('Parent',Hpanel,...
%       'Style', 'pushbutton',...
%       'Position', [170 140  60 20],...
%       'String', 'Elements',...
%       'CallBack',['element(''window'',''' ...
%             getappdata(Hfig,'rsName') ''');']);
speGUI.Hid.speMolWeight = uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'ForegroundColor', 'blue',...
   'FontSize', 10,...
   'HorizontalAlignment', 'left',...
   'Position', [20 110 210 25]);
speGUI.Hid.speCASregistry = uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'left',...
   'Position', [20 75 210 20]);
speGUI.Hid.speInChI = uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'left',...
   'Position', [20 35 210 40]);
speGUI.Hid.spePrimeId = uicontrol('Parent',Hpanel,...
   'Style', 'text',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment', 'left',...
   'Position', [20 15 210 20]);
speGUI.Hid.showSpeXml = uicontrol('Parent',Hpanel,...
   'Style', 'pushbutton',...
   'Position', [140 18 70 20],...
   'ForegroundColor', 'blue',...
   'BackgroundColor', [0.9 0.9 0.9],...
   'String','show XML',...
   'Callback', @viewSpeXml );


   function viewSpeXml(h,d)
      ReactionLab.Util.gate2primeData('show',...
          {'primeId',speGUI.CurrentSpecies.PrimeId});
   end

end