function plot3d(obj,molModelObj)
% plot(MolGeomFactoryObj,MolecularModelObj)

% Copyright 1999-2012 Michael Frenklach
% $Revision: 1.1 $
% Last modified: July 5, 2012

Haxes = axes('Parent',molModelObj.Hpanel,...
             'Units', 'normalized',...
             'OuterPosition',[0 0 1 1],...
             'AmbientLightColor','w');
hold on

aa = molModelObj.Geom3d.atoms;
for i1 = 1:length(aa)
   ai = aa(i1);
   setAtomColor(ai);
   Xc = ai.R * molModelObj.Hgeom.xSphere + ai.X;
   Yc = ai.R * molModelObj.Hgeom.ySphere + ai.Y;
   Zc = ai.R * molModelObj.Hgeom.zSphere + ai.Z;
   if strcmpi(ai.Element,'H')
      surf(Xc,Yc,Zc,'FaceColor','white',...
                    'EdgeColor','none',...
                    'FaceLighting','gouraud',...
                    'AmbientStrength',0.6,...
                    'DiffuseStrength',0.6,...
                    'SpecularStrength',0.9,...
                    'SpecularExponent',30,...
                    'SpecularColorReflectance',1 );
   else
      surf(Xc,Yc,Zc,'FaceColor',ai.Color,...
                    'EdgeColor','none',...
                    'FaceLighting','gouraud',...
                    'AmbientStrength',0.4,...
                    'DiffuseStrength',0.6,...
                    'SpecularStrength',0.9,...
                    'SpecularExponent',30,...
                    'SpecularColorReflectance',1 );
   end
end

bb = molModelObj.Geom3d.bonds;
for j1 = 1:length(bb)
   a1 = bb(j1).From;
   a2 = bb(j1).To;
   ro = bb(j1).Order;
   if     ro == 1,   draw10;
   elseif ro == 1.5, draw15;
   elseif ro == 2  , draw20;
   elseif ro == 3  , draw30;
   else
      error(['undefined reaction order ' num2str(ro)]);
   end
end

hold off

daspect(Haxes,[1 1 1]);
camlight right
%  light('Parent',Haxes','Position',[10 15 20],'Style','infinite');
light('Parent',Haxes,'Position',[-10 -15 -20],'Style','infinite');
%  camlight right
% light('Style','infinite');
% lighting gouraud       %   gouraud   phong
camproj(Haxes,'perspective');
% material([0.4,0.6,0.9,30,0]);
% material shiny
set(gcf,'Renderer','OpenGL');
rotate3d(Haxes,'on');
axis vis3d
axis(Haxes,'off');

drawnow


   function draw10
      drawCylinder(0.1,a1,a2,1);
   end

   function draw15
      [x,y,z] = ReactionLab.SpeciesData.SpeciesStructure.cylinder2P([0.1 0.1],30,...
                                                      a1.Coordinates,a2.Coordinates);
      surf(x,y,z,'FaceColor',a1.Color,...
                 'EdgeColor','none',...
                 'FaceLighting','gouraud',...
                 'AmbientStrength',0.4,...
                 'DiffuseStrength',0.6,...
                 'SpecularStrength',0.9,...
                 'SpecularExponent',30,...
                 'SpecularColorReflectance',1 );
      [x,y,z] = ReactionLab.SpeciesData.SpeciesStructure.cylinder2P(repmat(0.11,1,15),10,...
                                                      a1.Coordinates,a2.Coordinates);
      scatter3(x(:),y(:),z(:),8,a1.Color);
   end

   function draw20
      drawCylinder(0.07,a1,a2,1);
      drawCylinder(0.2, a1,a2,0.6);
   end
   function draw30
      drawCylinder(0.06,a1,a2,1);
      drawCylinder(0.12,a1,a2,0.5);
      drawCylinder(0.24,a1,a2,0.6);    
   end

   function setAtomColor(a)
      e = a.Element;
      switch upper(e)
         case 'C'
            a.Color = [0.85 0.85 0.85];
            a.R     = 0.77;
         case 'H'
            a.Color = [0.9999999 0.9999999 0.9999999];
            a.R     = 0.55;
         case 'O'
            a.Color = [1 0.16 0.16];
            a.R     = 0.64;
         case 'N'
            a.Color = [0.16 0.16 1];
            a.R     = 0.676;
         otherwise
            d = molModelObj.Hgeom.elementsData;
            ind = find(strcmpi(e,d(:,1)));
            if isempty(ind)
               error(['no match for element ' e]);
            end
            a.Color = d{ind,3};
            a.R     = d{ind,2};
      end
   end

   function drawCylinder(r,a1,a2,transp)
      [x,y,z] = ReactionLab.SpeciesData.SpeciesStructure.cylinder2P([r r r],30,...
                                                   a1.Coordinates,a2.Coordinates);
      if strcmpi(a1.Color,a2.Color)
         surf(x,y,z,'FaceColor',ai(j1).Color,...
                 'EdgeColor','none',...
                 'FaceAlpha', transp,...
                 'FaceLighting','gouraud',...
                 'AmbientStrength',0.4,...
                 'DiffuseStrength',0.6,...
                 'SpecularStrength',0.9,...
                 'SpecularExponent',30,...
                 'SpecularColorReflectance',1 );
      else
         surf(x([1 2],:),y([1 2],:),z([1 2],:),'FaceColor',a1.Color,...
                 'EdgeColor','none',...
                 'FaceAlpha', transp,...
                 'FaceLighting','gouraud',...
                 'AmbientStrength',0.4,...
                 'DiffuseStrength',0.6,...
                 'SpecularStrength',0.9,...
                 'SpecularExponent',30,...
                 'SpecularColorReflectance',1 ); 
         surf(x([2 3],:),y([2 3],:),z([2 3],:),'FaceColor',a2.Color,...
                 'EdgeColor','none',...
                 'FaceAlpha', transp,...
                 'FaceLighting','gouraud',...
                 'AmbientStrength',0.4,...
                 'DiffuseStrength',0.6,...
                 'SpecularStrength',0.9,...
                 'SpecularExponent',30,...
                 'SpecularColorReflectance',1 );
      end
   end

end