function window(rs)
% window(ReactionSetObj)
% sets the main window for ReactionSet obj

% Copyright 1999-2013 Michael Frenklach
% Created: February 25, 2013, myf

Hfig = figure('Position',[100 200 350 300],...
   'NumberTitle', 'off',...
   'Name', 'Reaction Model ',...
   'Tag', 'rxnset',...
   'MenuBar', 'none',...
   'Resize','off' );

figColor = get(Hfig,'Color');

uicontrol('Parent',Hfig,...
   'Style', 'text',...
   'BackgroundColor', figColor,...
   'HorizontalAlignment','left',...
   'FontSize', 14,...
   'FontWeight', 'bold', ...
   'Position', [20 250 280 25],...
   'String',['Title: ' rs.Title]);
uicontrol('Parent',Hfig,...
   'Style', 'text',...
   'BackgroundColor', figColor,...
   'HorizontalAlignment','left',...
   'FontSize', 14,...
   'Position', [20 220 300 25],...
   'String',['PrIMe ID: ' rs.PrimeId]);
uicontrol('Parent',Hfig,...
   'Style', 'pushbutton',...
   'Position', [300 220 40 20],...
   'HorizontalAlignment','left',...
   'String', 'View' ,....                
   'Callback', @viewModelXml );
uicontrol('Parent',Hfig,...
   'Style', 'text',...
   'BackgroundColor', figColor,...
   'HorizontalAlignment','left',...
   'FontSize', 14,...
   'Position', [20 190 290 25],...
   'String',['Source: ' rs.BiblioKey]);
uicontrol('Parent',Hfig,...
   'Style', 'pushbutton',...
   'Position', [300 190 40 20],...
   'HorizontalAlignment','left',...
   'String', 'View' ,....                
   'Callback', @ref );

uicontrol('Parent',Hfig,...
   'Style', 'pushbutton',...
   'ForegroundColor', 'blue',...
   'FontSize', 12,...
   'FontWeight', 'bold', ...
   'Position', [20 110 150 25],...
   'String','Reactions',...
   'Callback', @showReactions );
uicontrol('Parent',Hfig,...
   'Style', 'text',...
   'ForegroundColor', 'blue',...
   'BackgroundColor', figColor,...
   'HorizontalAlignment','left',...
   'FontSize', 12,...
   'FontWeight', 'bold', ...
   'Position', [180 110 40 25],...
   'String',num2str(rs.Reactions.Length));

uicontrol('Parent',Hfig,...
   'Style', 'pushbutton',...
   'ForegroundColor', 'blue',...
   'HorizontalAlignment','left',...
   'FontSize', 12,...
   'FontWeight', 'bold', ...
   'Position', [20 50 150 25],...
   'String','Species',...
   'Callback', @showSpecies );
uicontrol('Parent',Hfig,...
   'Style', 'text',...
   'ForegroundColor', 'blue',...
   'BackgroundColor', figColor,...
   'HorizontalAlignment','left',...
   'FontSize', 12,...
   'FontWeight', 'bold', ...
   'Position', [180 50 40 25],...
   'String',num2str(rs.Species.Length));

   function showSpecies(h,d)
      rs.Species.window;
   end

   function showReactions(h,d)
      rs.Reactions.window;
   end

   function viewModelXml(h,d)
      ReactionLab.Util.gate2primeData('show',{'primeId',rs.PrimeId});
   end

   function ref(h,d)
   % display bibliographic info
      b = ReactionLab.Util.PrIMeData.PrIMeBiblio(rs.BiblioId);
      b.view(rs.Title);
   end

end